# Azure Static Web Apps Configuration
# This file configures your deployment to Azure Static Web Apps

name: Baby Ceremony Digital - Azure Deployment

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build API
        run: |
          cd api
          npm ci
          npm run build

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/" # App source code path
          api_location: "api/dist" # Api source code path - pre-built
          output_location: "dist" # Built app content directory
          skip_api_build: true
        env:
          # Admin Authentication
          VITE_ADMIN_EMAIL: ${{ secrets.VITE_ADMIN_EMAIL }}
          VITE_ADMIN_PIN: ${{ secrets.VITE_ADMIN_PIN }}
          
          # Azure Storage Configuration
          VITE_AZURE_STORAGE_ACCOUNT: ${{ secrets.VITE_AZURE_STORAGE_ACCOUNT }}
          VITE_AZURE_STORAGE_KEY: ${{ secrets.VITE_AZURE_STORAGE_KEY }}
          VITE_AZURE_CONTAINER_RSVPS: ceremony-rsvps
          VITE_AZURE_CONTAINER_WISHES: ceremony-wishes
          VITE_AZURE_CONTAINER_PHOTOS: ceremony-photos
          VITE_AZURE_CONTAINER_DATA: ceremony-data

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"